'use client';

import { useState, useEffect } from 'react';
import { store } from '@/lib/store';

const SEVERITY_CONFIG: Record<string, { label: string; color: string; bg: string; border: string; icon: string }> = {
    critical: { label: 'Critical', color: 'text-red-800 dark:text-red-200', bg: 'bg-red-50 dark:bg-red-950', border: 'border-red-200 dark:border-red-800', icon: '🔴' },
    major: { label: 'Major', color: 'text-orange-800 dark:text-orange-200', bg: 'bg-orange-50 dark:bg-orange-950', border: 'border-orange-200 dark:border-orange-800', icon: '🟠' },
    moderate: { label: 'Moderate', color: 'text-yellow-800 dark:text-yellow-200', bg: 'bg-yellow-50 dark:bg-yellow-950', border: 'border-yellow-200 dark:border-yellow-800', icon: '🟡' },
    mild: { label: 'Mild', color: 'text-blue-800 dark:text-blue-200', bg: 'bg-blue-50 dark:bg-blue-950', border: 'border-blue-200 dark:border-blue-800', icon: '🔵' },
    none: { label: 'No interaction', color: 'text-green-800 dark:text-green-200', bg: 'bg-green-50 dark:bg-green-950', border: 'border-green-200 dark:border-green-800', icon: '✅' },
};

export default function InteractionsPage() {
    const [interactions, setInteractions] = useState(store.getInteractions());
    const [checking, setChecking] = useState(false);
    const [expandedId, setExpandedId] = useState<string | null>(null);
    const [toast, setToast] = useState('');
    const [lastChecked, setLastChecked] = useState<string | null>(null);

    useEffect(() => {
        const unsub = store.subscribe(() => setInteractions(store.getInteractions()));
        return () => { unsub(); };
    }, []);

    const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(''), 3000); };

    const handleRunCheck = () => {
        setChecking(true);
        setTimeout(() => {
            const results = store.runInteractionCheck();
            setInteractions(results);
            setChecking(false);
            setLastChecked(new Date().toLocaleTimeString());
            const warnings = results.filter(r => r.severity !== 'none');
            showToast(warnings.length > 0
                ? `⚠️ Found ${warnings.length} interaction${warnings.length > 1 ? 's' : ''} requiring attention`
                : '✅ No significant interactions found!');
        }, 1500);
    };

    const handleShare = (interaction: typeof interactions[0]) => {
        const text = `⚠️ Drug Interaction Alert\n${interaction.medA.name} + ${interaction.medB.name}\nSeverity: ${interaction.severity.toUpperCase()}\n${interaction.description}\n\nGenerated by MedMinder`;
        if (navigator.share) {
            navigator.share({ title: 'Drug Interaction Alert', text }).catch(() => { });
        } else {
            navigator.clipboard.writeText(text);
            showToast('📋 Copied to clipboard — paste to share');
        }
    };

    const active = interactions.filter(i => i.severity !== 'none');
    const safe = interactions.filter(i => i.severity === 'none');
    const meds = store.getMedications().filter(m => m.status !== 'discontinued');

    return (
        <div className="space-y-6 animate-fade-in">
            {toast && (
                <div className="fixed bottom-6 right-6 z-50 bg-gray-900 text-white px-5 py-3 rounded-xl shadow-2xl text-sm font-medium animate-slide-up">{toast}</div>
            )}

            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                    <h1 className="font-display text-3xl font-bold text-gray-900 dark:text-white">Drug Interactions</h1>
                    <p className="text-gray-500 dark:text-gray-400 mt-1">
                        Checking {meds.length} active medications · {interactions.length} pair{interactions.length !== 1 ? 's' : ''} analyzed
                        {lastChecked && <span> · Last checked: {lastChecked}</span>}
                    </p>
                </div>
                <button onClick={handleRunCheck} disabled={checking} className="btn-primary inline-flex items-center gap-2 cursor-pointer">
                    {checking ? (
                        <><svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" /></svg> Analyzing...</>
                    ) : (
                        <><svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M9.75 3.104v5.714a2.25 2.25 0 0 1-.659 1.591L5 14.5M9.75 3.104c-.251.023-.501.05-.75.082m.75-.082a24.301 24.301 0 0 1 4.5 0m0 0v5.714c0 .597.237 1.17.659 1.591L19.8 15.3M14.25 3.104c.251.023.501.05.75.082M19.8 15.3l-1.57.393A9.065 9.065 0 0 1 12 15a9.065 9.065 0 0 0-6.23.693L5 14.5m14.8.8 1.402 1.402c1.232 1.232.65 3.318-1.067 3.611A48.309 48.309 0 0 1 12 21c-2.773 0-5.491-.235-8.135-.687-1.718-.293-2.3-2.379-1.067-3.61L5 14.5" /></svg> Run Interaction Check</>
                    )}
                </button>
            </div>

            {/* Warnings */}
            {active.length > 0 && (
                <div className="space-y-3">
                    <h2 className="text-lg font-semibold text-gray-900 dark:text-white">⚠️ Interactions Found ({active.length})</h2>
                    {active.sort((a, b) => ['critical', 'major', 'moderate', 'mild'].indexOf(a.severity) - ['critical', 'major', 'moderate', 'mild'].indexOf(b.severity)).map(interaction => {
                        const config = SEVERITY_CONFIG[interaction.severity];
                        const isExpanded = expandedId === interaction.id;
                        return (
                            <div key={interaction.id} className={`rounded-2xl border ${config.border} ${config.bg} overflow-hidden`}>
                                <button onClick={() => setExpandedId(isExpanded ? null : interaction.id)} className="w-full text-left p-5 cursor-pointer">
                                    <div className="flex items-start gap-3">
                                        <span className="text-xl mt-0.5">{config.icon}</span>
                                        <div className="flex-1">
                                            <div className="flex items-center gap-2 flex-wrap">
                                                <span className={`text-xs font-bold px-2 py-0.5 rounded-full ${config.color} ${config.bg} border ${config.border}`}>{config.label.toUpperCase()}</span>
                                                <span className="font-semibold text-gray-900 dark:text-white">{interaction.medA.name}</span>
                                                <span className="text-gray-400">+</span>
                                                <span className="font-semibold text-gray-900 dark:text-white">{interaction.medB.name}</span>
                                            </div>
                                            <p className={`text-sm mt-1 ${config.color}`}>{interaction.description}</p>
                                        </div>
                                        <svg className={`w-5 h-5 text-gray-400 transition-transform ${isExpanded ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" /></svg>
                                    </div>
                                </button>
                                {isExpanded && (
                                    <div className="px-5 pb-5 space-y-4 border-t border-gray-200/50">
                                        <div className="mt-4">
                                            <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Mechanism</h4>
                                            <p className="text-sm text-gray-700 dark:text-gray-300">{interaction.mechanism}</p>
                                        </div>
                                        {interaction.symptoms.length > 0 && (
                                            <div>
                                                <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Watch For</h4>
                                                <div className="flex flex-wrap gap-1.5">{interaction.symptoms.map((s, i) => (
                                                    <span key={i} className="text-xs px-2 py-1 rounded-lg bg-white/60 dark:bg-black/20 text-gray-700 dark:text-gray-300">{s}</span>
                                                ))}</div>
                                            </div>
                                        )}
                                        <div>
                                            <h4 className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-1">Recommendations</h4>
                                            <ul className="space-y-1">{interaction.recommendations.map((r, i) => (
                                                <li key={i} className="text-sm text-gray-700 dark:text-gray-300 flex items-start gap-2">
                                                    <span className="text-primary-500 mt-0.5">→</span> {r}
                                                </li>
                                            ))}</ul>
                                        </div>
                                        <div className="flex items-center justify-between pt-2">
                                            <span className="text-xs text-gray-400">Source: {interaction.source}</span>
                                            <button onClick={() => handleShare(interaction)} className="text-xs text-primary-600 hover:text-primary-700 font-medium cursor-pointer flex items-center gap-1">
                                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M7.217 10.907a2.25 2.25 0 1 0 0 2.186m0-2.186c.18.324.283.696.283 1.093s-.103.77-.283 1.093m0-2.186 9.566-5.314m-9.566 7.5 9.566 5.314m0 0a2.25 2.25 0 1 0 3.935 2.186 2.25 2.25 0 0 0-3.935-2.186Zm0-12.814a2.25 2.25 0 1 0 3.933-2.185 2.25 2.25 0 0 0-3.933 2.185Z" /></svg>
                                                Share with Doctor
                                            </button>
                                        </div>
                                    </div>
                                )}
                            </div>
                        );
                    })}
                </div>
            )}

            {/* Safe Pairs */}
            {safe.length > 0 && (
                <div>
                    <h2 className="text-lg font-semibold text-gray-900 dark:text-white mb-3">✅ No Interaction ({safe.length})</h2>
                    <div className="grid gap-2">
                        {safe.map(i => (
                            <div key={i.id} className="card py-3 flex items-center gap-3">
                                <span className="text-green-500">✅</span>
                                <span className="text-sm text-gray-700 dark:text-gray-300"><strong>{i.medA.name}</strong> + <strong>{i.medB.name}</strong></span>
                                <span className="text-xs text-gray-400 ml-auto">Safe to combine</span>
                            </div>
                        ))}
                    </div>
                </div>
            )}

            <div className="card bg-blue-50 dark:bg-blue-950/20 border-blue-200 dark:border-blue-800">
                <p className="text-sm text-blue-800 dark:text-blue-200">
                    ⚕️ <strong>Medical Disclaimer:</strong> This tool uses pharmaceutical databases and AI analysis for educational purposes only. Always consult your healthcare provider or pharmacist before making medication changes.
                </p>
            </div>
        </div>
    );
}
